# Caso esse arquivo não seja carregado, o mod irá carregar as configurações padrão

[Config]

Key = 84 ; Tecla para ativar o mod
Zoom = 350.0 ; Valor do zoom no radar

# Lista de teclas: https://www.indigorose.com/webhelp/ams/Program_Reference/Misc/Virtual_Key_Codes.htm